config/routes.rb
Todo::Application.routes.draw do
  devise_for :users
  resources :overview, :only => :index
  resources :watches, :only => [:index, :create, :destroy]
  resources :users, :only => [] do
    resources :lists, :only => [:index, :show], :controller => 'users/lists'
  end
  resources :lists do
    resources :tasks, :controller => 'lists/tasks', :only => [] do
      member do
        put :done
        put :undone
      end
    end
  end
  root :to => "overview#index"
end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :tasks, :dependent => :destroy
  has_many :watches, :dependent => :destroy
  belongs_to :user
  validates_presence_of :name

  accepts_nested_attributes_for :tasks, :allow_destroy => true, :reject_if => proc { |attr| attr['description'].blank? }

  scope :public, where(:private => false)
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :list
  validates_presence_of :description

  def done!
    update_attribute(:done, true)
  end

  def undone!
    update_attribute(:done, false)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :avatar, :name

  validates_presence_of :name

  has_many :lists, :dependent => :destroy
  has_many :watches, :dependent => :destroy

  scope :lasts_signed_in, order('current_sign_in_at DESC')

  mount_uploader :avatar, AvatarUploader

  def watch?(list)
    !!watch(list)
  end

  def watch(list)
    watches.find_by_list_id(list)
  end
end

app/models/watch.rb
class Watch < ActiveRecord::Base
  belongs_to :list
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/lists/tasks_controller.rb
class Lists::TasksController < InheritedResources::Base
  before_filter :authenticate_user!
  belongs_to :list
  respond_to :js, :only => [:done, :undone]

  def done
    resource.done!
  end

  def undone
    resource.undone!
  end
end

app/controllers/lists_controller.rb
class ListsController < InheritedResources::Base
  before_filter :authenticate_user!
  respond_to :html, :json

  def new
    @list = List.new
    @list.tasks.build
  end

  protected

  def begin_of_association_chain
    current_user
  end

  def collection
    @lists ||= end_of_association_chain.page params[:page]
  end
end

app/controllers/overview_controller.rb
class OverviewController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.lasts_signed_in.limit(10).where("id <> ?", current_user.id)
  end
end

app/controllers/users/lists_controller.rb
class Users::ListsController < InheritedResources::Base
  before_filter :authenticate_user!
  before_filter :check_list_accessibility, :only => :show
  belongs_to :user
  actions :index, :show

  protected

  def collection
    @lists ||= end_of_association_chain.public
  end

  private

  def check_list_accessibility
    redirect_to watches_path if resource.private?
  end
end

app/controllers/watches_controller.rb
class WatchesController < InheritedResources::Base
  before_filter :authenticate_user!
  actions :index, :create, :destroy
  respond_to :html, :json

  def create
    create! { user_list_path(resource.list.user.id, resource.list_id) }
  end

  protected

  def begin_of_association_chain
    current_user
  end

  def collection
    @watches ||= end_of_association_chain.page params[:page]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class(path)
    current_page?(path) ? "active" : ""
  end
end

app/helpers/lists_helper.rb
module ListsHelper
  def add_task_link(list_form)
    html = list_form.simple_fields_for :tasks, list_form.object.tasks.build, :child_index => 'NEW_RECORD' do |task_form|
      render('task', :task_form => task_form)
    end

    link_to_function 'Add new task', "$('#tasks-fields').append('#{escape_javascript(html)}'.replace(/NEW_RECORD/g, new Date().getTime() ));", :class => 'add-task', :title => "Add new task"
  end

  def remove_task_link(task_form)
    if task_form.object.new_record?
      link_to_function("Remove", "$(this).parents('.task-fields').remove();")
    else
      link_to_function("Remove", "var parent = $(this).parents('.task-fields'); parent.find('.delete').val('1'); parent.hide();")
    end
  end
end

app/helpers/users/lists_helper.rb
module Users::ListsHelper
  def link_to_watch(list)
    if current_user.watch?(list)
      link_to "Unwatch", watch_path(current_user.watch(list)), :method => :delete, :confirm => "Are you sure?", :title => "Unwatch"
    else
      link_to "Watch", watches_path(:watch => { :list_id => list.id }), :method => :post, :title => "Watch"
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo App</title>
    <%= stylesheet_link_tag 'bootstrap-1.2.0.min' %>
    <%= stylesheet_link_tag 'base' %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div class="topbar-wrapper">
      <div class="topbar">
        <div class="topbar-inner">
          <div class="container">
            <h3><%= link_to 'Todo List', root_path, :title => "Todo List" %></h3>
            <ul class="nav secondary-nav">
              <% if user_signed_in? %>
                <%= content_tag(:li, current_user.name, :class => "user-name") %>
                <%= content_tag(:li, link_to("My lists", lists_path, :title => "My lists"), :class => active_class(lists_path)) %>
                <%= content_tag(:li, link_to("Watched lists", watches_path, :title => "Watched lists"), :class => active_class(watches_path)) %>
                <%= content_tag(:li, link_to("Edit profile", edit_user_registration_path, :title => "Edit profile"), :class => active_class(edit_user_registration_path)) %>
                <%= content_tag(:li, link_to("Sign out", destroy_user_session_path, :method => :delete, :title => "Sign out")) %>
                <%= content_tag(:li, link_to(image_tag(current_user.avatar.thumb.url, :class => "thumb-profile", :alt => current_user.name), edit_user_registration_path, :title => "Edit profile")) %>
              <% else %>
                <%= content_tag(:li, link_to("Sign in", new_user_session_path, :title => "Sign in"), :class => active_class(new_user_session_path)) %>
                <%= content_tag(:li, link_to("Sign up", new_user_registration_path, :title => "Sign up"), :class => active_class(new_user_registration_path)) %>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="span12 columns">
          <% if notice %>
            <p class='alert-message block-message success'><%= notice %></p>
          <% end %>

          <% if alert %>
            <p class='alert-message block-message error'><%= alert %></p>
          <% end %>

          <%= yield %>
        </div>
        <% if user_signed_in? %>
          <div class="span4 columns">
            <div class="well">
              <p><%= link_to "Create a new list", new_list_path, :class => 'btn primary large', :title => "Create a new list" %></p>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </body>
</html>

app/views/lists/_form.html.erb
<div class="inputs">
  <%= f.input :name, :label => "List name", :required => true %>
  <%= f.input :private, :hint => "no one can see this list if private is marked" %>

  <div class="page-header">
    <h5>Tasks</h5>
  </div>

  <div id="tasks-fields">
    <%= f.simple_fields_for :tasks do |task_form| %>
      <%= render 'task', :task_form => task_form %>
    <% end %>
  </div>

  <p id="add-task"><%= add_task_link(f) %></p>
</div>

app/views/lists/_task.html.erb
<div class='task-fields'>
  <%= task_form.input :description, :label => "Task" %>
  <%= task_form.hidden_field :_destroy, :class => :delete %>
  <p><%= remove_task_link(task_form) %></p>
</div>

app/views/lists/edit.html.erb
<div class="page-header">
  <h2>Edit list</h2>
</div>

<%= simple_form_for(resource) do |f| %>
  <%= f.error_notification %>

  <%= render 'form', :f => f %>

  <div class="actions">
    <%= f.button :submit, "Update", :class => 'btn' %>
    or <%= link_to "cancel", lists_path, :title => "Cancel" %>
  </div>
<% end %>

app/views/lists/index.html.erb
<div class="page-header">
  <h2>Lists</h2>
</div>

<% if collection.any? %>
  <table class='zebra-striped'>
    <thead>
      <tr>
        <th>Name</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% collection.each do |resource| %>
        <tr>
          <td><%= link_to resource.name, resource, :title => resource.name %></td>
          <td>
            <%= link_to 'Edit', edit_resource_path(resource), :title => "Edit" %> |
            <%= link_to 'Destroy', resource, :method => :delete, :confirm => 'Are you sure?', :title => "Destroy" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>You dont have any list. Create a new one clicking <%= link_to 'here', new_list_path %></p>
<% end %>

<%= paginate collection %>

app/views/lists/new.html.erb
<div class="page-header">
  <h2>New list</h2>
</div>

<%= simple_form_for(resource) do |f| %>
  <%= f.error_notification %>

  <%= render 'form', :f => f %>

  <div class="actions">
    <%= f.button :submit, "Create", :class => 'btn' %>
    or <%= link_to "cancel", lists_path, :title => "Cancel" %>
  </div>
<% end %>

app/views/lists/show.html.erb
<div id="list">
  <div class="page-header">
    <h2><%= resource.name %> <small><%= resource.private ? 'Private' : 'Public' %></small></h2>
  </div>

  <div id='tasks'>
    <% resource.tasks.each do |task| %>
      <div id="<%= dom_id task %>" class="task clearfix <%= 'done' if task.done? %>">
        <p class="description"><%= task.description %></p>
        <%= link_to '#', task.done ? undone_list_task_path(resource, task) : done_list_task_path(resource, task), :method => :put, :remote => true %>
      </div>
    <% end %>
  </div>

  <p class="action"><%= link_to "Edit this list", edit_list_path(resource), :title => "Edit this list" %></p>
  <p class="back"><%= link_to "<< Back", lists_path, :title => "Back" %></p>
</div>

app/views/lists/tasks/done.js.erb
$("#<%= dom_id resource %> a").attr("href", '<%= undone_list_task_path(@list, resource) %>');
$("#<%= dom_id resource %>").addClass('done');

app/views/lists/tasks/undone.js.erb
$("#<%= dom_id resource %> a").attr("href", '<%= done_list_task_path(@list, resource) %>');
$("#<%= dom_id resource %>").removeClass('done');

app/views/overview/index.html.erb
<div class="page-header">
  <h2>Last 10 logged users:</h5>
</div>

<div id='users'>
  <% @users.each do |user| %>
    <div class="user clearfix">
      <%= link_to(image_tag(user.avatar.thumb.url, :class => "thumb-profile", :alt => user.name), user_lists_path(user), :title => user.name) %>
      <%= link_to user.name, user_lists_path(user), :title => user.name %>
    </div>
  <% end %>
</div>

app/views/users/lists/index.html.erb
<div class="page-header">
  <h2>Lists of <%= parent.name %></h2>
</div>

<% if collection.any? %>
  <table class='zebra-striped'>
    <thead>
      <tr>
        <th>Name</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% collection.each do |resource| %>
        <tr>
          <td><%= link_to resource.name, user_list_path(parent, resource) %></td>
          <td><%= link_to_watch resource %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p><%= parent.name %> does not have any list.</p>
<% end %>

app/views/users/lists/show.html.erb
<div id="list">
  <div class="page-header">
    <h2><%= resource.name %> <small>from <%= parent.name %></small></h2>
  </div>

  <div id='tasks'>
    <% resource.tasks.each do |task| %>
      <div id="<%= dom_id task %>" class="task clearfix <%= 'done' if task.done? %>">
        <p class="description"><%= task.description %></p>
      </div>
    <% end %>
  </div>

  <p class="action"><%= link_to_watch resource %></p>
  <p class="back"><%= link_to "<< Back", watches_path, :title => "Back" %></p>
</div>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/watches/index.html.erb
<div class="page-header">
  <h2>Watched lists</h2>
</div>

<% if collection.any? %>
  <table class='zebra-striped'>
    <thead>
      <tr>
        <th>List name</th>
        <th>User name</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% collection.each do |resource| %>
        <tr>
          <td><%= link_to resource.list.name, user_list_path(resource.list.user, resource.list) %></td>
          <td><%= resource.list.user.name %></td>
          <td><%= link_to "Stop watching", resource, :method => :delete, :confirm => "Are you sure?" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>You are not watching any list.</p>
<% end %>

<%= paginate collection %>